
networks:
  lemp82:
    name: lemp82

volumes:
  lemp82_db: 
    name: lemp82_db
    driver: local
  phpmyadmin_data:
    name: phpmyadmin_data
    driver: local

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-lemp82}
    restart: unless-stopped
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/app
      - phpmyadmin_data:/var/www/html/pma
      - .env:/var/www/html/app/.env
    depends_on:
      - php
      - redis
      - mysql
      - phpmyadmin
      - mail_hog
    networks:
      - lemp82
  
  php:
    build:
      context: ./php
      dockerfile: php.dockerfile
      args: 
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-1000}
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/html/app
      - .env:/var/www/html/app/.env
    networks:
      - lemp82

  mysql:
    image: mariadb:10.6 
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - lemp82_db:/var/lib/mysql
    networks:
      - lemp82

  phpmyadmin:
    image: phpmyadmin:fpm-alpine 
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: ${DB_PORT} 
    volumes:
      - phpmyadmin_data:/var/www/html
    depends_on:
      - mysql
    networks:
      - lemp82

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - lemp82

  composer:
    build:
      context: ./php
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-1000}
    container_name: composer
    volumes:
      - ./src:/var/www/html/app/
      - .env:/var/www/html/app/.env
    working_dir: /var/www/html
    depends_on:
      - php
    user: ${USER:-lemp82}
    profiles: ["composer"]
    entrypoint: ["composer", "--ignore-platform-reqs"]
    networks:
      - lemp82

  mail_hog:
    build:
      context: ./mail_hog
      dockerfile: mail_hog.dockerfile
    container_name: mail_hog
    logging:
      driver: "none"
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - lemp82

  artisan:
    build:
      context: ./php
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-lemp82}
    container_name: artisan
    volumes:
      - ./src:/var/www/html/app/
      - .env:/var/www/html/app/.env
    depends_on:
      - mysql
    working_dir: /var/www/html/app
    user: ${USER:-lemp82}
    profiles: ["artisan"]
    entrypoint: ["php", "/var/www/html/app/artisan"]
    networks:
      - lemp82

  npm:
    image: node:20.15.1-alpine
    container_name: npm
    volumes:
      - ./src:/var/www/html/app
      - .env:/var/www/html/app/.env
    ports:
      - 5173:5173
    working_dir: /var/www/html/app/
    user: "${UID}:${GID}"
    profiles: ["npm"]
    entrypoint: ["npm"]
    networks:
      - lemp82

  npx:
    image: node:20.15.1-alpine
    container_name: npx 
    volumes:
      - ./src:/var/www/html/app/
      - .env:/var/www/html/app/.env
    working_dir: /var/www/html/app/
    user: "${UID}:${GID}"
    profiles: ["npm"]
    entrypoint: ["npx"]
    networks:
      - lemp82

